interactions:
- request:
    body: '{"direction": "both", "labels": ["_acquisition", "_imageFiles"], "rootRecordId":
      "nonexistent_asdfasdfasdfdfasffds", "maxdepth": 2}'
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['131']
      Content-Type: [application/json]
      User-Agent: [python-requests/2.9.1]
    method: POST
    uri: https://geobigdata.io/catalog/v1/traverse
  response:
    body: {string: !!python/unicode '{"status":"400 Bad Request","message":"The supplied
        rootRecordId does not exist in catalog."}'}
    headers:
      connection: [keep-alive]
      content-length: ['93']
      content-type: [application/json]
      date: ['Thu, 12 May 2016 18:07:04 GMT']
      server: [Apache-Coyote/1.1]
      via: [kong/0.5.2]
    status: {code: 400, message: Bad Request}
version: 1
